# Generated by Django 4.2.2 on 2023-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='interns',
            field=models.ManyToManyField(to='myapp.intern'),
        ),
    ]
