# Generated by Django 4.2.2 on 2023-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_company_employee_owner_intern_owner_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(related_name='companies', to='myapp.owner'),
        ),
        migrations.AddField(
            model_name='intern',
            name='employees',
            field=models.ManyToManyField(related_name='interns', to='myapp.employee'),
        ),
    ]
