# Generated by Django 4.2.2 on 2023-07-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_employee_owner_remove_intern_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='employees',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
