# Generated by Django 4.2.2 on 2023-07-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_owner_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.owner'),
            preserve_default=False,
        ),
    ]
